### ISSUE TITLE
Mod 3 Authorize access with AAD login issue

### ISSUE THREAD

**Issue by dabrock51** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#104]
# Module: 03
#### Step: 03

Description of issue:
When attempting to login using the new Azure SQL Admin account the following error occurs:

Sorry, but we’re having trouble signing you in.
AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.

**Comment by sherzyang** [comment]
Hi @dabrock51 thanks for raising this issue, sorry you're having that experience. I think it is part of a larger issue with the product. I will look into it.

**Comment by sherzyang** [comment]
Hi @dabrock51 thanks for raising this issue, sorry you're having that experience. I think it is part of a larger issue with the product. I will look into it.

**Comment by sherzyang** [comment]
Hi @dabrock51, for your issue, your user account may fall under a group which is not supported. 

We have a note in the steps: "A Microsoft account (a user account from Outlook, Gmail, Hotmail or Yahoo, for example) is not supported for the Azure Active Directory administrator for Azure SQL Database. As a workaround, you can create an Azure Active Directory group named DBA and add your user account to it. Alternatively, you can skip Exercise 2." 

Since I don't know what type of account you're using, I'll close this issue. If you're still facing an error, we can open a new ticket. Thanks!
