### ISSUE TITLE
Lab 1 - Reference to check subscription info

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#138]
# Module: 01
#### Step: 02-03

Description of issue
Those steps do not apply with Cloud Slice.
![image](https://user-images.githubusercontent.com/46898093/170300261-e11fa626-0bd7-4f3c-83db-77ed03eaf94a.png)

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
