### ISSUE TITLE
Lab 1 - Remove the steps to download AdventureWorksDW2017.bak

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#139]
# Module: 01
#### Step:  08-12

Description of issue
Those steps are no longer required with Cloud Slice, when the student download the files to D drive, they can access the backup file from there. Just need to move the file into the backup folder (‎C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup.)
![image](https://user-images.githubusercontent.com/46898093/170302146-ff40a1f5-33fe-43c4-9dfe-ca0feb5aa143.png)

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
