### ISSUE TITLE
Lab 3 - Instructions to configure Networking settings are out of date

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#140]
# Module: 03
#### Step: 03-04

Description of issue
The instructions and screenshots are out of date.
![image](https://user-images.githubusercontent.com/46898093/170307380-78d69335-e741-49ec-b4a8-675dff51d80f.png)

![image](https://user-images.githubusercontent.com/46898093/170307648-34bad053-b1ed-4d7d-b8f9-94cd098eae36.png)

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
