### ISSUE TITLE
Lab 3 - Remove note that is no longer relevant in Cloud Slice

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#141]
# Module: 03
#### Step: 01

Description of issue
As we are using Cloud Slice, please remove the following notes:

"Important: A Microsoft account (a user account from Outlook, Gmail, Hotmail or Yahoo, for example) is not supported for the Azure Active Directory administrator for Azure SQL Database. As a workaround, you can create an Azure Active Directory group named DBA and add your user account to it. Alternatively, you can skip Exercise 2."

"Do not remove any of the resources created in this lab as they will be used in subsequent lab exercises."

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
