### ISSUE TITLE
Lab 4 - Pre-Staging task 4

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#144]
# Module: 04
#### Step: 04

Description of issue
Out of date instructions and screenshots:
(Click on Show **firewall settings** (above the server name that you just copied). Click on + Add client IP as highlighted below and then click Save.)
![image](https://user-images.githubusercontent.com/46898093/170708625-8635dd30-c855-46c8-bff5-52c39e987bb6.png)

![image](https://user-images.githubusercontent.com/46898093/170708899-2937b4d0-0280-4c53-98d4-20aeced7595d.png)

**Comment by TesterTesterson1004** [comment]
Looks like Skillable updated this in their Cloudslice version to reflect the current phrasing:

![image](https://user-images.githubusercontent.com/49700217/173913798-26dca0cf-ac3a-490c-862c-b1b92d364017.png)

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
