### ISSUE TITLE
Lab 4 - Task 1 out of date instructions

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#145]
# Module: 04
#### Step: 01

Description of issue
1- "If you're not already in the Azure portal, navigate back to https://portal.azure.com. You may need to login again. In the search bar at the top of the Azure Portal, type SQL, and click on SQL databases. **This task will use the AdventureWorks database you created in Lab 3.** Click on the database name.

Needs to be updated in Cloud Slice as this step refers to Pre-Staging.

**Comment by TesterTesterson1004** [comment]
This also looks like it has been updated by Skillable to reflect the Cloudslice version.

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
