### ISSUE TITLE
Lab 6 -  Exercise 3 password info is wrong

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#146]
# Module: 06
#### Step: 06

Description of issue

"You will be prompted for credentials to login to your database. Use the credentials you created in Exercise 1. Login: labadmin Password: **Azur3Pa$$**"

Password is wrong, in the Exercise 1, Task: Deploy an Azure SQL Database from a template, step 3 the password has only one $

- SQL Administrator Login Password: **Azur3Pa$**

**Comment by TesterTesterson1004** [comment]
This appears to have been corrected in the Cloudslice version -- I was just checking and the password for this lab now matches Github through to the end.  i.e., it has both $$:

 
![image](https://user-images.githubusercontent.com/49700217/173924454-ee605ac7-4225-4501-a4ea-a25bc42cb75e.png)

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
