### ISSUE TITLE
Lab 6 - Runbook schedule instructions are out of date

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#147]
# Module: 06
#### Step: 27-28

Description of issue
Out of date instructions, you can create a schedule in the schedule navigation menu option, but to link it to a runbook you need to navigate to the runbook.

![image](https://user-images.githubusercontent.com/46898093/170715070-1cda6005-9c44-4a6c-bbba-931b888ced06.png)

![image](https://user-images.githubusercontent.com/46898093/170715955-5e2225c6-af2d-401d-9992-e46ce3cfdef6.png)

I suggest to remove steps 27-28 and then add extra steps to link the created schedule to the runbook after step 31.

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
