### ISSUE TITLE
No need to create Resource group in Azure for labs as resource group DP-300-Lab01lod<user id> already exists. Cannot create rg in any case

### ISSUE THREAD

**Issue by janeroughan** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#149]
# Module: 01
#### Step: 08
Resource group DP-300-Lab01lod<userid> already exists and no resource group can be created in Lab slice.
Repro Steps.
1.Remove instruction to create resource group and refer to the existing resource group DP-300-Lab01lod<userid>

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
