### ISSUE TITLE
Lab 02 Exercise 2 Task 2, point 2, Do we need to change Firewalls and virtual network to Network.

### ISSUE THREAD

**Issue by janeroughan** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#150]
# Module: 02
#### Step: 02

Description of issue
There is a reference to "Firewalls and virtual networks" under security to add your ip address rule. I think this is now just "Networking" under security.

Repro steps:

1.Rename Firewalls and virtual networks to Networking
1.Remove screen shot
1.

**Comment by JeffSmalley** [comment]
Jane is correct that this change is needed. Can someone update the instructions???
![Screenshot 2022-05-24 103644](https://user-images.githubusercontent.com/16696370/174690068-69c9f593-7274-423b-a982-229d3d1dbb05.png)


Regards,
Jeff Smalley MCT
Chicagoville

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
