### ISSUE TITLE
Module 2 instructions not correctly reflecting Azure options

### ISSUE THREAD

**Issue by SQLtattoo** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#151]
# Module: 02
#### Step:  2

Description of issue
"Firewalls and virtual networks" option do not exist on Azure Portal under Security section as depicted in the photo of the lab instructions. Instead it now reads just "Networking".

Repro steps:

1.
1.
1
![Screenshot 2022-05-31 140306](https://user-images.githubusercontent.com/11569518/171159506-e6f53c72-1eb1-454d-8bf1-28011c4f6628.png)
.

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
