### ISSUE TITLE
Module 3 outdated instructions

### ISSUE THREAD

**Issue by SQLtattoo** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#152]
# Module: 03
#### Step: 04

Description of issue
The picture and the instructions talk about an option "Show firewall settings" that do not exist anymore in Azure. It now reads "Show networking settings". 

Repro steps:

1.
1.
1
![Screenshot 2022-05-31 141503](https://user-images.githubusercontent.com/11569518/171174681-b2c6632b-d5da-4792-81bd-ca25e629a76b.png)
.

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
