### ISSUE TITLE
Module 6, Lab 6 Labadmin user

### ISSUE THREAD

**Issue by janeroughan** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#153]
# Module: 6
#### Step: 06

Description of issue
PAssword for labadmin reads Azur3Pa$$, should be Azur3Pa$

Repro steps:

1.Rename the password and remove the additional $ Dollar sign
1.
1.

**Comment by TesterTesterson1004** [comment]
See also - https://github.com/MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure/issues/146  (seems to have been fixed)

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
