### ISSUE TITLE
Lab 3 exercise 2

### ISSUE THREAD

**Issue by afandrews777** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#155]
# Module: 3
#### Step: the entire exercise is not doable

Description of issue: We can't create a user to add to a group in AAD and then set as the SQL database admin. We cant test the user by logging into SSMS. Please allow us to  create user on AAD or give us a user and its password to add into an AAD group and then set as the SQL DB admin. We need the user and password to test the login. We can't do any part of this exercise. 

Repro steps:

1.
1.
1.

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
