### ISSUE TITLE
Password issue in Lab 6, Ex 3 step 6

### ISSUE THREAD

**Issue by afandrews777** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#156]
# Module: 6
#### Step: 00

Description of issue: This steps has the wrong password. It should be  Azur3Pa$  but it is listed as Azur3Pa$$

Repro steps:

1.
1.
1.

**Comment by TesterTesterson1004** [comment]
See also https://github.com/MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure/issues/146, appears to have been fixed

**Comment by JulianePadrao** [comment]
This repository has been decommissioned and is not in use.

To access lab exercises and instructions for Microsoft DP-300 learning content, see [DP-300: Administering Relational Databases on Microsoft Azure](https://github.com/MicrosoftLearning/dp-300-database-administrator).

If this issue is still active in the new repository, please open a new request in the new repository.

Thank you,
