### ISSUE TITLE
Extremely weak guidance/suggestions for demos

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure#94]
Most of the demo slides contain insignificant guidance for what a demo should be; at least one demo refers to a demo app that no longer compiles correctly.

While as a certified DBA and experienced instructor, yes, I can come up with my own demo... but I could also come up with my own course, and slides and lab instructions, too.

The idea of MOC has been that it is a consistent, (ideally) high-quality experience, and no matter which MCT delivers it, the students should experience the same content (although, yes, instructors are a value-add).

In addition, although I have worked with SQL for (ahem, mumble, mumble....) many years, I -- like most MCTs and most DBAs -- have not used every single feature or spent time in depth with every possible permutation. In prepping a course, I often *learn* new things. 

Therefore, it is my opinion that a one-sentence "walk through this feature" is not an adequate demo instruction. (If there are more steps, instructions or references somewhere else, then I apologize and ask for a link to find them).

If it is now out of scope for a course to include instructions for MCTs, I think at the very least a reference on the demo slide to where to find samples, guidance, documentation, or videos of the feature should be included.

**Comment by sherzyang** [comment]
@boomalator Thanks for your feedback about the demo slides. Many factors lead to content decisions including time needed for sustained engineering, the needs of multiple programs utilizing the same learning material, and learning design with a focus on hands-on-labs rather than text-heavy slides. That said, we are working to respond to issues logged in GitHub and to update material. Thanks for voicing your thoughts and your patience.
